name: Create Release

on:
  release:
    types:
      - created
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore --no-cache

      - name: Test
        run: dotnet test -c Release --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Build
        run: dotnet build ./src/JacksonVeroneze.NET.Pagination/JacksonVeroneze.NET.Pagination.csproj -c Release --no-restore

      - name: Pack
        run: dotnet pack ./src/JacksonVeroneze.NET.Pagination/JacksonVeroneze.NET.Pagination.csproj -c Release /p:Version=${{ github.event.release.tag_name }} --include-symbols --include-source --no-restore

      - name: Publish Package
        run: dotnet nuget push ./src/JacksonVeroneze.NET.Pagination/bin/Release/JacksonVeroneze.NET.Pagination.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_PUBLISH_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate